const RESEND_API_URL = "https://api.resend.com/emails";

interface SendEmailParams {
  to: string;
  subject: string;
  html: string;
  text: string;
  from: string;
  apiKey: string;
}

export async function sendEmail(params: SendEmailParams): Promise<{ id: string }> {
  const response = await fetch(RESEND_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${params.apiKey}`,
    },
    body: JSON.stringify({
      from: params.from,
      to: [params.to],
      subject: params.subject,
      html: params.html,
      text: params.text,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Resend API error (${response.status}): ${errorText.substring(0, 200)}`
    );
  }

  return response.json();
}

export function buildEmailHtml(
  fullName: string,
  analysis: string,
  businessType: string
): string {
  const analysisHtml = analysis
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n/g, "<br>");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Business Reality Check</title>
</head>
<body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background:#111;border-radius:16px;border:1px solid rgba(255,255,255,0.08);">

          <!-- Header -->
          <tr>
            <td style="padding:32px 32px 16px;text-align:center;">
              <div style="font-size:24px;font-weight:800;color:#fff;margin-bottom:4px;">
                HelpMe<span style="color:#22d3ee;">Business</span>
              </div>
              <div style="font-size:12px;color:#71717a;letter-spacing:1px;text-transform:uppercase;">
                Business Reality Check
              </div>
            </td>
          </tr>

          <!-- Greeting -->
          <tr>
            <td style="padding:16px 32px 8px;">
              <div style="font-size:16px;color:#e4e4e7;line-height:1.6;">
                Hi <strong style="color:#fff;">${fullName}</strong>,
              </div>
              <div style="font-size:14px;color:#a1a1aa;line-height:1.6;margin-top:8px;">
                Thanks for sharing your ${businessType || "business"} details. Here's your personalized analysis from our AI advisor:
              </div>
            </td>
          </tr>

          <!-- Analysis Card -->
          <tr>
            <td style="padding:16px 32px;">
              <div style="background:linear-gradient(135deg,rgba(34,211,238,0.05),rgba(139,92,246,0.05));border:1px solid rgba(34,211,238,0.15);border-radius:12px;padding:24px;">
                <div style="font-size:14px;color:#e4e4e7;line-height:1.8;">
                  ${analysisHtml}
                </div>
              </div>
            </td>
          </tr>

          <!-- CTA -->
          <tr>
            <td style="padding:16px 32px;text-align:center;">
              <div style="font-size:13px;color:#71717a;margin-bottom:16px;">
                Want a deeper dive with a human expert?
              </div>
              <a href="https://helpmebusiness.com" style="display:inline-block;background:linear-gradient(135deg,#22d3ee,#3b82f6);color:#000;font-weight:700;font-size:14px;padding:12px 32px;border-radius:12px;text-decoration:none;">
                Book a ₹999 Clarity Call →
              </a>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:24px 32px;border-top:1px solid rgba(255,255,255,0.06);text-align:center;">
              <div style="font-size:11px;color:#52525b;line-height:1.6;">
                This analysis was generated by AI and is for informational purposes only.<br>
                © ${new Date().getFullYear()} HelpMeBusiness. All rights reserved.
              </div>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export function buildEmailText(fullName: string, analysis: string): string {
  return `Hi ${fullName},

Thanks for sharing your business details with HelpMeBusiness. Here's your AI-generated Business Reality Check:

${analysis}

---
Want a deeper dive? Book a ₹999 Clarity Call at https://helpmebusiness.com

This analysis was generated by AI and is for informational purposes only.
© ${new Date().getFullYear()} HelpMeBusiness`;
}
